name: Test Workflow CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - working-directory: ./client
      - name: Test Workflow CI
      - run: cd client && npm install && npm run test
